version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    networks:
      - my_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" 
    networks:
      - my_network

  nginx:
    build: ./nginx
    
    volumes:
      - ./public:/app/public  
    ports:
      - '80:80'
      - '443:443'  
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:
